name: voice-clone
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.20.0
  - scipy>=1.9.0
  - matplotlib>=3.5.0
  - pytorch>=1.12.0
  - torchaudio>=0.12.0
  - pytorch-cuda=11.8
  - pip
  - pip:
    - librosa>=0.10.0
    - soundfile>=0.10.0